//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecordBook.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Activities.
        /// </summary>
        public static string Label_AllActivities {
            get {
                return ResourceManager.GetString("Label_AllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating {0} Records.
        /// </summary>
        public static string Label_CalculatingRecords {
            get {
                return ResourceManager.GetString("Label_CalculatingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Label_End {
            get {
                return ResourceManager.GetString("Label_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eval version limited to {0} distance categories.
        /// </summary>
        public static string Label_EvalCategoryLimit {
            get {
                return ResourceManager.GetString("Label_EvalCategoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eval version locked to evaluate previous {0} days.  See settings page to unlock..
        /// </summary>
        public static string Label_EvalHistoryLimit {
            get {
                return ResourceManager.GetString("Label_EvalHistoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremes.
        /// </summary>
        public static string Label_Extremes {
            get {
                return ResourceManager.GetString("Label_Extremes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Settings.
        /// </summary>
        public static string Label_ListSettings {
            get {
                return ResourceManager.GetString("Label_ListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Label_Max {
            get {
                return ResourceManager.GetString("Label_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Avg. Speed.
        /// </summary>
        public static string Label_MaxAvgSpeed {
            get {
                return ResourceManager.GetString("Label_MaxAvgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Distance.
        /// </summary>
        public static string Label_MaxDistance {
            get {
                return ResourceManager.GetString("Label_MaxDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Elevation.
        /// </summary>
        public static string Label_MaxElevation {
            get {
                return ResourceManager.GetString("Label_MaxElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Pace.
        /// </summary>
        public static string Label_MaxPace {
            get {
                return ResourceManager.GetString("Label_MaxPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Temp..
        /// </summary>
        public static string Label_MaxTemperature {
            get {
                return ResourceManager.GetString("Label_MaxTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Time.
        /// </summary>
        public static string Label_MaxTime {
            get {
                return ResourceManager.GetString("Label_MaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max TRIMP.
        /// </summary>
        public static string Label_MaxTRIMP {
            get {
                return ResourceManager.GetString("Label_MaxTRIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max TSS.
        /// </summary>
        public static string Label_MaxTSS {
            get {
                return ResourceManager.GetString("Label_MaxTSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Label_Min {
            get {
                return ResourceManager.GetString("Label_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Elevation.
        /// </summary>
        public static string Label_MinElevation {
            get {
                return ResourceManager.GetString("Label_MinElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Grade.
        /// </summary>
        public static string Label_MinGrade {
            get {
                return ResourceManager.GetString("Label_MinGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Temp..
        /// </summary>
        public static string Label_MinTemperature {
            get {
                return ResourceManager.GetString("Label_MinTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Label_New {
            get {
                return ResourceManager.GetString("Label_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Label_Now {
            get {
                return ResourceManager.GetString("Label_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now/Then.
        /// </summary>
        public static string Label_NowThen {
            get {
                return ResourceManager.GetString("Label_NowThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Label_Rank {
            get {
                return ResourceManager.GetString("Label_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Label_Record {
            get {
                return ResourceManager.GetString("Label_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Book.
        /// </summary>
        public static string Label_RecordBook {
            get {
                return ResourceManager.GetString("Label_RecordBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Label_Reset {
            get {
                return ResourceManager.GetString("Label_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Columns.
        /// </summary>
        public static string Label_SelectedColumns {
            get {
                return ResourceManager.GetString("Label_SelectedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then.
        /// </summary>
        public static string Label_Then {
            get {
                return ResourceManager.GetString("Label_Then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Distance for One Day.
        /// </summary>
        public static string Label_TotalDistanceForOneDay {
            get {
                return ResourceManager.GetString("Label_TotalDistanceForOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time for One Day.
        /// </summary>
        public static string Label_TotalTimeForOneDay {
            get {
                return ResourceManager.GetString("Label_TotalTimeForOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Label_Units {
            get {
                return ResourceManager.GetString("Label_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where Does It Rank.
        /// </summary>
        public static string Label_WhereDoesItRank {
            get {
                return ResourceManager.GetString("Label_WhereDoesItRank", resourceCulture);
            }
        }
    }
}
